import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

const lexend = Lexend({
  variable: "--font-lexend",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.variable} antialiased font-main relative min-h-screen bg-black overflow-hidden text-white`}
      >
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-[-20%] left-[-10%] w-[60%] h-[60%] bg-gradient-to-br from-purple-700 via-pink-600 to-indigo-500 opacity-20 rounded-full filter blur-2xl"></div>
          <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] bg-gradient-to-tr from-blue-600 via-teal-500 to-green-400 opacity-20 rounded-full filter blur-2xl"></div>
        </div>
        {children}
      </body>
    </html>
  );
}
